name: Publish to Docker
on:
  push:
    branches:
      - main
permissions:
  packages: write
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@v2

      - name: step 1 - Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: step 2 - Set up a cache for maven
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
 
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Add your test steps here if needed...
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/chfle/spring_todo_app
          tags: type=sha
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build container
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
